const mongoose = require("mongoose");

const invoiceSchema = new mongoose.Schema({
  name: { type: String },
  client_id: { type: String },
  invoice_no: { type: String },
  bill_of_lading: { type: String },
  billing_address: { type: String },
  billing_contact: { type: String },
  billing_gstin: { type: String },
  billing_pan: { type: String },
  billing_state: { type: String },
  brokername: { type: String },
  buyers_order_no: { type: String },
  dated: { type: String },
  dated2: { type: String },
  delivery_date: { type: String },
  destination: { type: String },
  dispatch_doc_no: { type: String },
  dispatch_through: { type: String },
  motor_v_no: { type: String },
  other_ref: { type: String },
  shipping_address: { type: String },
  shipping_contact: { type: String },
  shipping_gstin: { type: String },
  shipping_pan: { type: String },
  shipping_state: { type: String },
  shipping_company_name: { type: String },
  billing_company_name: { type: String },
  inr_no: { type: String },
  ack_no: { type: String },
  ack_date: { type: String },
  delivery_note: { type: String },
  terms_of_payment: { type: String },
  terms_of_delivery: { type: String },
  shipping_email: { type: String },
  billing_email: { type: String },
  e_way_no: { type: String },
  freight: { type: String },
  files: [
    {
        desc_id: { type: String },
        Desc: { type: String },
        product_id: { type: String },
        quantity: { type: String },
        sac: { type: String },
        rate: { type: String },
        unit: { type: String },
        cgst: { type: String },
        igst: { type: String },
        sgst: { type: String },
        gst_type: { type: String },
     
    },
  ],
});

module.exports = mongoose.model("Invoice", invoiceSchema);
